### PR TITLE
Synergistic Plots 

### PR DESCRIPTION
**Pull request by gwenchee**
This PR includes the jupyter notebook and dat file that were used to produce the 3D plots of synergistic results. 

Idle Capacity
Depleted U
HLW

### CODE REVIEW

**Comment by gwenchee** [comment]
@pep8speaks pep8ify

**Comment by gwenchee** [comment]
@pep8speaks pep8ify

**Comment by gtw2** [comment]
Nice, you got it to rotate :D these plots look much better

**Comment by gwenchee** [comment]
Thanks @gtw2 :D

**Pull request merged**
