### PR TITLE
Pyre Electrorefiner OAT

### PR DESCRIPTION
**Pull request by gtw2**
This PR adds OAT analysis for 3 key components of the elctrorefiner, as well as adding the functions.py file which includes some SQL functions.

### CODE REVIEW

**Comment by gtw2** [comment]
@pep8speaks pep8ify

**Comment by gtw2** [comment]
@pep8speaks pep8ify

**Review by gwenchee — CHANGES_REQUESTED** [review]
You should add the isotope_total_cum function to a file in the scripts folder instead of leaving the function in the notebook. This applies to all notebooks in the dakota/oat/pyre directory. Other than that, it looks good!

**Review by gwenchee — APPROVED** [review]
Nice

**Pull request merged**
